import os

ROOT_DIR=os.environ["ROOT_DIR"]+"/"
FROM_ORCHID_DIR = ROOT_DIR + "files_from_orchid/codelists_for_website/"
CODELIST_EXPANSIONS = FROM_ORCHID_DIR + "flatlists_for_website.txt"
CODELIST_DEFINITIONS = FROM_ORCHID_DIR + "logical_definitions_for_website.txt"
CODELIST_MEDS_DEFINITIONS = FROM_ORCHID_DIR + "logical_definitions_for_medications_for_website.txt"
RSC_IMAGE_FILENAME = "rsc_image.png"
SHARED_CSS_FILENAME = "shared.css"

AUTHORING=os.environ["AUTHORING"]+"/"
PHENOTYPE_LIST = AUTHORING + "/phenotypes_to_publish.txt"
SNOMED_RELEASE_IDENTIFIER_FILE = AUTHORING + "/snomed_release_identifier.txt"
PHENOTYPE_DESCRIPTIONS_DIR = AUTHORING + "phenotypes/"
CODELIST_DESCRIPTIONS_DIR = AUTHORING + "codelists/"
DOCS_DIR = AUTHORING + "docs/"

OUTPUT_STAGING_ROOT_DIR = os.environ["OUTPUT_STAGING_ROOT_DIR"]+"/"
PHENOTYPES_OUTPUT_INDEX = OUTPUT_STAGING_ROOT_DIR + "phenotypes_index.html"
PHENOTYPES_OUTPUT_DESCRIPTIONS_DIR = OUTPUT_STAGING_ROOT_DIR + "phenotypes/"
CODELISTS_OUTPUT_INDEX = OUTPUT_STAGING_ROOT_DIR + "codelists_index.html"
CODELISTS_OUTPUT_DESCRIPTIONS_DIR = OUTPUT_STAGING_ROOT_DIR + "codelists/"
DOCS_OUTPUT_DIR = OUTPUT_STAGING_ROOT_DIR + "docs/"
DOCS_OUTPUT_INDEX = DOCS_OUTPUT_DIR + "index.html"
CODELISTS_OUTPUT_FOR_DOWNLOAD_DIR = OUTPUT_STAGING_ROOT_DIR + "codelists_for_download/"

DATA_FOR_POWER_BI_DIR = os.environ["DATA_FOR_POWER_BI_DIR"]+"/"
DATA_EXTRACTION_FILES_DIR = os.environ["DATA_EXTRACTION_FILES_DIR"]+"/"